### ISSUE TITLE
Changes to configuration documentation

### ISSUE THREAD

**Issue by ptgolden** [dredge-bio/dredge#56]
Configuration documentation should be clearer and more worked out

**Comment by ptgolden** [comment]
Instead of editing the text, I'm going to give it a try from scratch, following the video tutorial, as suggested by a reviewer. I think it might make sense to separate the actual configuration page (with inputs and so on) from the documentation.

**Comment by ptgolden** [comment]
If that's the case, I can change the configuration page so that the left column has the editable text inputs, and the right column has the expected directory layout

**Comment by tintori** [comment]
Just adding some thoughts: All the reviewers commented on how the instructions seemed quite spread out, between the configuration page, the videos, the text of the paper, and the supplementary "detailed instructions" part. I think if the configuration page is as detailed (or almost as detailed) as the video, then we can scrap the supplementary instructions file, which would be great. 
But that leaves us with three simultaneous challenges for the configuration page, (1) adding a lot more detail, (2) including a sandbox example with a real dataset that we provide, so that users can successfully go through the process once before trying on their own, and (3) making everything clearer. 
Especially because of the clarity part, I wonder if there's a way to have all the input fields and instructions in one linear column, but have most of it tucked away until the user calls up that part of the instructions. Like if the user could click on something to unfurl the full instructions for each item, as well as the precise instructions for the example dataset.

**Comment by tintori** [comment]
(About the example dataset—I'm thinking that the human neuronal data would be the best to showcase, because it's the smallest. I'm happy to add that to your work after Monday night, or you can include it in the first draft yourself if you'd like, completely up to you.)

**Comment by ptgolden** [comment]
DONE
